# Generated by Django 3.0.2 on 2020-06-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCal', '0002_remove_event_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='date',
        ),
    ]
