# Generated by Django 3.0.2 on 2020-06-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCal', '0003_auto_20200626_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
